# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run localnet
      run: |
        brew install aptos 
        aptos node run-local-testnet --force-restart --assume-yes &
        echo "Waiting for localnet to be ready..."
        while ! curl --output /dev/null --silent --head --fail http://127.0.0.1:8080; do
          sleep 5
        done
    - name: Run tests
      run: swift test -v
